ispindel:
  prometheus:
    host: "http://192.168.0.2"
    port: "9090"
  littlebock:
    serverAdress: "www.littlebock.fr"
    serverUrl: "/api/log/ispindle/XXXX/YYYY"
  name: "ispindel"
  synchronisation:
    interval: "15m"
    timeout: "90d"
